### ISSUE TITLE
Documentation for using partools with quantreg?

### ISSUE THREAD

**Issue by znmeb** [matloff/partools#15]
I've seen a number of mentions that partools / software alchemy can be used with quantreg / quantile regression. But I've been unable to find any documentation / examples on how to do that. Is there any?

**Comment by clarkfitzg** [comment]
Running `grep` for `quantreg` and `rq(` don't turn anything up in the source. I'd be happy to see one though.

**Comment by znmeb** [comment]
@clarkfitzg The only place I've seen more than a mention of it is in the table of contents for <https://www.amazon.com/Parallel-Computing-Data-Science-Examples/dp/1466587016/>. I'm guessing there might be a code snippet there but I can't find one elsewhere.

**Comment by clarkfitzg** [comment]
Here you go: https://github.com/matloff/partools/blob/master/inst/examples/quantreg.R

**Comment by znmeb** [comment]
Thanks!!

**Comment by clarkfitzg** [comment]
You're welcome. Thanks for taking an interest.
